modLoader="kotlinfml"
loaderVersion="[1.4,)"

issueTrackerURL="https://github.com/AngrySoundTech/CivMaster/issues"
displayURL="https://github.com/AngrySoundTech/CivMaster"
authors="AngrySoundTech"
credits="Mr_Little_Kitty, iykHvflvfR, Gjum"

[[mods]]
modId="civmaster"
version="${version}"
displayName="CivMaster"
description=""

[[dependencies.civmaster]]
modId="forge"
mandatory=true
versionRange="[28.1.92,)"
ordering="NONE"
side="BOTH"
